server:
  host: "127.0.0.1"
  port: 8080
  cors_origins: ["*"]

redis:
  url: "redis://127.0.0.1:6379"
  pool_size: 5
  database: 1
  rate_limit:
    max_requests: 60
    window_seconds: 120
    punishment_threshold: 10
    punishment_duration: 120

mongodb:
  url: "mongodb://127.0.0.1:27017"
  database: "hoyoverse"

logging:
  level: "debug"
  format: "pretty" 